//
//  CompoundDetails.swift
//  MetNet
//
//  Created by Alexander Munoz on 1/20/17.
//  Copyright © 2017 Alexander Munoz. All rights reserved.
//

import UIKit

class CompoundDetails: UIViewController {

    var compoundSelectedTag = Int()
    
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var contentLabel: UILabel!
    @IBOutlet weak var popupScrollView: UIScrollView!
    
    let compoundsInfo = [
        1 : (title: "Info",
             description: "Here's how to use the app!"),
        2 : (title: "Galactose",
             description: "Galactose is a monosaccharide hexose that is made from the catabolism of lactose into galactose and glucose. \n\nReactivity: Galactose undergoes phosphorylation by galactokinase, and then galactose-1-phosphate uridyl transferase and an epimerase finish the conversion of galactose to glucose."),
        3 : (title: "Epimerase",
             description: "After galactose is formed from the catabolism of lactose into galactose and glucose, galactose is converted into glucose so that it can enter the glycolytic pathway for energy production. Galactose is converted to glucose via galactokinase, galactose-1-phosphate uridyl transferase, and finally an epimerase to convert the molecule from the galactose epimer to the glucose epimer."),
        4 : (title: "Glucose",
             description: "Glucose is a monosaccharide hexose. The body tries to maintain homeostatic levels of blood glucose at about 5.5 mM (100 mg/dL).\n\nSynthesis: Blood glucose can be introduced by -\n(1) the breakdown of disaccharide sugars: sucrose, lactose, and maltose catabolism for example, will all yield glucose monomers\n(2) glycogenolysis: during the post-absorptive state, the initial response of decreasing blood sugar is for the liver to start catabolizing glycogen reserves to release glucose into the blood stream\n(3) gluconeogenesis: the brain largely prefers glucose as a source of energy. As a result if blood glucose levels run low, the liver and renal cortex will compensate by performing gluconeogenesis and releasing the newly formed glucose to the blood\n(4) uptake from serum: hepatocytes and pancreatic islet beta cells have a GLUT2 low-affinity glucose receptor such that they uptake glucose proportional to the serum level. On the other hand, adipocytes and muscle cells have a GLUT4 high-affinity glucose receptor such that they import glucose whenever available.\n\nReactivity: Glucose is first phosphorylated at carbon 6 to form glucose-6-phosphate. This phosphorylation attaches a negatively charged phosphate group to the sugar, which prevents it from escaping the cell. This phosphorylation essentially traps the molecule in the cell, pushing the equilibrium toward the products of the downstream catabolic pathway."),
        5 : (title: "GK/HK",
             description: "The glucokinase and hexokinase enzymes phosphorylate carbon-6 of glucose molecules in the cell in an irreversible reaction that uses one ATP equivalent. This phosphorylation attaches a negatively charged phosphate to the sugar molecule to trap the glucose in the cell because GLUT transporters are specific for glucose not phosphorylated glucose.\n\nHexokinase is in all tissues and is inhibited by the glucose-6-phosphate product. Hexokinase has a low Km, which implies that it has maximum catalytic activity at low glucose concentration. Glucokinase, on the other hand, is exclusively in liver cells pancreatic beta islet cells and is induced by insulin. Glucokinase acts as glucose sensor along with GLUT2 as it has a high Km, yielding activity proportional to glucose concentration."),
        6 : (title: "G6Pase",
             description: "The glucose-6-phosphatase enzyme is an irreversible enzyme that converts glucose-6-phosphate to glucose. This enzyme is inhibited by insulin, such that it will be active only during gluconeogenesis. This irreversible enzyme finishes the recreation of glucose during gluconeogenesis, and it is found in the lumen of the endoplasmic reticulum in hepatocytes. Glucose-6-phosphate is transported to the ER lumen and then glucose is transported back to cytoplasm where it can diffuse out of the cell using GLUT transporters. Absence of glucose-6-phosphatase in skeletal muscle means muscle glycogen cannot serve as a source of blood glucose."),
        7 : (title: "G6P",
             description: "Glucose-6-phosphate is the molecule formed after phosphorylation of carbon-6 on glucose. Unlike unphosphorylated glucose, G6P cannot escape from the cell through the GLUT transporters. Thus, following this phosphorylation, G6P will follow one of the catabolic or anabolic pathways (unless gluconeogenesis is being performed in the hepatocytes where G6P can be dephosphorylated by glucose-6-phosphatase to yield a glucose monomer which can be subsequently released from the cell).\n\nReactivity: G6P can proceed down a catabolic pathway or one of two anabolic pathways. The catabolism of G6P proceeds via glycolysis (G6P is broken down to form ATP and NADH). The first anabolic option for G6P is glycogenesis, where G6P is used to make the storage form of glucose: glycogen. The second anabolic option for G6P is a shunt from glycolytic flux: the Pentose Phosphate Pathway. This pathway produces NADPH for intracellular reductive chemistry and ribose sugars for nucleotide synthesis during cell growth."),
        8 : (title: "G6P-DH",
             description: "The glucose-6-phosphate dehydrogenase enzyme is the rate-determining step in the pentose phosphate pathway (PPP). The enzyme converts some of the glucose-6-phosphate that would typically go down the glycolytic pathway into ribulose-5-phosphate and NADPH. The ribulose-5-phosphate can be converted into the ribose nucleotide precursor via further chemistry. The NADPH product serves a very important purpose within the cell. While NADH is almost immediately oxidized by the electron transport chain in the mitochondria causing its levels to remain low intracellularly, NADPH retains high intracellular levels. Thus, instead of being used for energy, NADPH can be used for intracellular reductive chemistry such as the glutathionine antioxidant functionality.\n\nControl: Because G6P-DH is the rate-determining step in the PPP, control over the flux into PPP largely occurs here. Insulin activates the enzyme - as expected, when energy is high in the cell, the cell can contribute more G6P toward growth and nucleotide synthesis. Furthermore, the pathway experiences negative feedback where the NADPH product inhibits the pathway and the NADP+ reactant activates the enzyme."),
        9 : (title: "R5P",
             description: "Ribulose-5-phosphate is an intermediate in the Pentose Phosphate Pathway, an anabolic shunt off of glycolysis. R5P can be converted into ribose, a precursor to nucleotide synthesis for cellular growth and division."),
        10 : (title: "R5P-Iso",
              description: "Ribulose-5-phosphate isomerase converts ribulose-5-phosphate to ribose-5-phosphate. Riboses are important precursors for nucleotide synthesis for cellular growth and division."),
        11 : (title: "Ribose",
              description: "Riboses are downstream products in the Pentose Phosphate Pathway, a shunt off of glycolysis.  Riboses are important precursors for nucleotide synthesis for cellular growth and division."),
        12 : (title: "Mutase",
              description: "Beta-phosphoglucomutase catalyzes the conversion of glucose-6-phosphate to glucose-1-phosphate, repositioning the phosphate group to carbon-1 as a step in the construction of the glycogen structure during glycogenesis."),
        13 : (title: "G1P",
              description: "Glucose-1-phosphate is a product in glycogenesis. The repositioning of the phosphate on G6P occurs via beta-phosphoglucomutase to begin the construction of glycogen via G1P monomers."),
        14 : (title: "UDP-G Pase",
              description: "UDP-glucose phosphorylase catalyzes the conversion of G1P to UDP-glucose. The UDP nucleotide is a good leaving group, so this conversion activates glucose for glucosyltransferase reactivity. The enzyme uses one UTP equivalent and releases a pyrophosphate side-product."),
        15 : (title: "UDP-glucose",
              description: "UDP-glucose is glucose with an additional UDP nucleotide attached to carbon-1. This UDP nucleotide is a good leaving group, thus activating glucose for glucosyltransferase reactivity, increasing the rate of the downstream glycogen formation reactions with the better leaving group."),
        16 : (title: "Glyc synth",
              description: "Glycogen synthase catalyzes the conversion of UDP-glucose to alpha-1,4-glycogen to form the basic unbranched form of glycogen during glycogenesis. Note that this step is irreversible and a different enzyme is required for glycogenolysis.\n\nControl: Glycogen synthase is the rate-limiting step in glycogenesis so much control occurs here. Glycogen synthase is activated by insulin as we would expect - we want to store excess glucose as glycogen after the cell is energetically satisfied. In the liver, glucagon inhibits the enzyme activity so that the liver does not perform glycogenesis during energetic starvation. AMP, which is present in high concentrations during energetic starvation, inhibits glycogen synthase in the muscle. Epinephrine, a hormone that attempts to acutely increase blood glucose levels in response to stress (i.e. fight or flight response), inhibits glycogen synthase in both the liver and the muscle."),
        17 : (title: "1,4-glycogen",
              description: "Alpha-1,4-glycogen is the storage form of glucose. It is a straight chain of glucose monomers in this unbranched form. Liver glycogen is broken down to maintain constant blood glucose level. Muscle glycogen is broken down to provide glucose to the muscle during exercise. Glycogen is stored in the cellular cytoplasm as granules. Each granule has a protein core with polyglucose chains radiating outward to form a sphere. Linear chains have highest density of glucose near center. Branched chains have highest density at periphery (allowing a more rapid release of glucose on demand). The 1,4 form of glycogen is unbranched."),
        18 : (title: "Branching",
              description: "The irreversible branching enzyme converts alpha-1,4-glycogen to alpha-1,6-glycogen, thus adding a branch to the glycogen chain. Branched glycogen has higher density at the periphery of the spherical granule, allowing for a more rapid release of glucose on demand."),
        19 : (title: "1,6-glycogen",
              description: "Alpha-1,6-glycogen is the branched connection form in the storage form of glucose: glycogen. This branched bond allows the spherical glycogen granules to have a higher density at the periphery, allowing for a more rapid release of glucose on demand."),
        20 : (title: "Debranching",
              description: "The debranching enzyme is used to catalyze the hydrolysis of the branches in a glycogen granule chain. The first alpha-1-4 bond after an alpha-1-6 bond is cleaved by the enzyme and that released chain is reattached to the end of the other accompanying glycogen strand. Then, the remaining monomer after the alpha-1-6 bond is cleaved off, leaving a glucose monomer and an alpha-1-4 glycogen strand that can be cleaved per normal catabolic reactivity."),
        21 : (title: "Glyc Pase",
              description: "Glycogen phosphorylase catalyzes the conversion of alpha-1-4-glycogen to glucose-1-phosphate. This catabolic step breaks down to glycogen into its glucose monomers such that the glucose can be broken down to form energy for the cell.\n\nControl: This is the rate-determining step of glycogenolysis, and it is under hormonal control. Intuitively, insulin and ATP, signs of high energy, inhibit glycogen phosphorylase. On the other hand, glucagon activates the enzyme in the liver and AMP and epinephrine activate the enzyme in muscle. The enzyme is activated under signs of a low-energy environment such that energy stores can be catabolized."),
        22 : (title: "PGI",
              description: "The phosphoglucoisomerase enzyme converts glucose-6-phosphate to its fructose-6-phosphate isomer. This isomerization essentially pops another alcohol group out of the ring where it is separated from the core sugar ring by one intermediate carbon. When the alcohol group is separated from the ring, it can be phosphorylated downstream (in fact in the next step catalyzed by PFK)."),
        23 : (title: "F6P",
              description: "Fructose-6-phosphate is an isomerized form of glucose-6-phosphate that has one of its alcohol groups separated from the core sugar ring such that the alcohol is sterically available for phosphorylation, which will then proceed with further downstream catabolism of the sugar’s breakdown in the glycolysis pathway."),
        24 : (title: "PFK-2",
              description: "The hepatocyte phosphofructokinase-2 enzyme phosphorylates fructose-6-phosphate to form fructose-2,6-bisphosphate, using one ATP equivalent. The product fructose-2,6-bisphosphate activates phosphofructokinase-1. Because phosphofructokinase-2 is activated by insulin, hepatocytes can override the ATP inhibition of phosphofructokinase-1 via insulin’s activation of phosphofructokinase-2 and subsequent activation of phosphofructokinase-1. Thus, hepatocytes can continue to run glycolysis to generate metabolic precursors even if they are energetically satisfied.\n\nControl: Phosphofructokinase-2 is under liver hormonal control. It is activated by insulin and inhibited by glucagon. Thus, insulin will override the typical ATP inhibition of glycolysis in hepatocytes."),
        25 : (title: "F-2,6-BP",
              description: "Fructose-2-6-bisphosphate is a phosphorylated product of fructose-6-phosphate produced by liver hepatocytes that cannot proceed to downstream glycolytic catabolism. Instead, its function is to activate the phosphofructokinase-1 enzyme. Because PFK-1 is inhibited by ATP, hepatocytes can activate PFK-2 in the presence of insulin to generate F-2,6-BP and activate PFK-1. Thus, in the presence of insulin, hepatocytes can override the ATP inhibition of glycolysis and use insulin to continue generating metabolic precursors even if they’re energetically satisfied."),
        26 : (title: "PFK-1",
              description: "Phosphofructokinase-1 phosphorylates fructose-6-phosphate to form fructose-1,6-bisphosphate in an irreversible reaction that uses one ATP equivalent. This step of the reaction separates the prep and payoff phases of glycolysis. In the prep phase, energy is put in to phosphorylate a glucose monomer. Before the end of the prep phase, the glucose monomer can go down several pathways, including glycolysis, the Pentose Phosphate Pathway, and glycogenesis. However after the phosphofructokinase-1 irreversible step, the resulting fructose-1,6-bisphosphate molecule will finish glycolysis and be converted to pyruvate. The payoff phase results in energy extraction from the phosphorylated fructose-1,6-bisphosphate molecule.\n\nControl: Phosphofructokinase-1 is the rate-limiting step in glycolysis, so much control of the entire glycolytic pathway occurs here. When the cell is energetically satisfied and ATP or citrate are present, phosphofructokinase-1 is inhibited. However, during the low-energy state, AMP activates the enzyme. More control over phosphofructokinase-1 occurs via phosphofructokinase-2 in the liver, see PFK-2 for more details."),
        27 : (title: "F-1,6-BPase",
              description: "Fructose-1,6-bisphosphatase is an anabolic enzyme in the gluconeogenesis pathway to replace the irreversible phosphofructokinase-1 step. The step irreversibly hydrolyzes the carbon-1 phosphate on fructose-1,6-bisphosphate to yield fructose-6-phosphate.\n\nControl: As fructose-1,6-bisphosphatase is the rate-limiting step in gluconeogenesis, it is under substantial hormonal control. "),
        28 : (title: "F-1,6-BP",
              description: "Fructose-1,6-bisphosphate is the turning point between the prep phase and the payoff phase of glycolysis. After fructose-1,6-bisphosphate is generated, the glycolysis pathway will be followed because the phosphofructokinase-1 step to generate frutocse-1,6-bisphosphate is irreversible."),
        29 : (title: "Aldo",
              description: "Fructose-bisphosphate aldolase splits fructose-1,6-bisphosphate into dihydroxyacetone-phosphate (DHAP) and glyceraldehyde-3-phosphate (GADP) in a reversible retro-aldol reaction. This lysing releases to phosphorylated molecules so that neither can escape from the cell. The two released molecules will be further catabolized in glycolysis to extract energy."),
        30 : (title: "GADP",
              description: "Glyceraldehyde-3-phosphate (also seen as G3P) is a glycolytic intermediate following the splitting of fructose-1,6-bisphosphate. The glyceraldehyde-3-phosphate piece continues with glycolysis while the other piece of the split must be converted to glyceraldehyde-3-phosphate to proceed with glycolysis."),
        31 : (title: "TIM",
              description: "Triosephosphate isomerase catalyzes the conversion of dihydroxyacetone-phosphate to glyceraldehyde-3-phosphate. This conversion allows the dihydroxyacetone-phosphate product from the aldolase split to proceed down glycolysis, as only the glyceraldehyde-3-phosphate piece is a reactant for further glycolytic catabolic reactions."),
        32 : (title: "DHAP",
              description: "Dihydroxyacetone-phosphate is one of the two products from the aldolase split of fructose-1,6-bisphosphate. The dihydroxyacetone-phosphate piece does cannot directly proceed down further catabolic glycolysis reactions but must first be converted to the other product of the aldolase splitting: glyceraldehyde-3-phosphate. However, dihydroxyacetone-phosphate also forms a precursor for the glycerol-3-phosphate backbone of triglycerides, so it can proceed down that anabolic pathway as well. Dihydroxyacetone-phosphate is the pathway by which fructose enters glycolysis. Because fructose enters glycolysis after the main phosphofructokinase-1 control point, fructose will be largely catabolized regardless of the energetic necessities of the cell. Thus, fructose will provide a spike of energy even if the cell is already energetically satisfied."),
        33 : (title: "Aldo-B",
              description: "Following phosphorylation to fructose-1-phosphate by fructokinase, fructose-1-phosphate-aldolase (aldolase-B) lyses the fructose product into dihydroxyacetone-phosphate and glyceraldehyde. The dihydroxyacetone-phosphate product can be converted to glyceraldehyde-3-phosphate to proceed with further catabolic glycolysis reactions."),
        34 : (title: "Fructose",
              description: "Fructose is a hexose isomer of glucose that can be generated by the catabolism of the sucrose disaccharide. Fructose is catabolized to enter glycolysis for energy extraction, except instead of entering glycolysis at the normal glucose entry point like glucose and galactose, fructose enters downstream. Because, fructose enters the glycolytic pathway after the main glycolysis phosphofructokinase-1 control point, fructose is quickly catabolized, regardless of the energetic needs of the cell. Thus, fructose will result in an ATP spike even if the cell is energetically satisfied."),
        35 : (title: "G3P-s",
              description: "The glycerol-3-phosphate shuttle is a method of transporting reduced energy carrier into the mitochondria and also generates the glycerol-3-phosphate backbone of triglycerides (the storage unit for fatty acids in the cell). In the shuttle, one NADH equivalent is used to convert dihydroxyacetone-phosphate to glycerol-3-phosphate and NAD+. The glycerol-3-phosphate unit can then be used as a backbone for triglyceride synthesis. In addition, glycerol-3-phosphate can enter the mitochondria, where it can react with FAD+ to regenerate dihydroxyacetone-phosphate and an additional FADH2. This shuttle thus essentially transfers an NADH from the cytoplasm to an FADH2 in the mitochondrial matrix, while also generating the glycerol-3-phosphate intermediate which can be used for triglyceride synthesis."),
        36 : (title: "G3P",
              description: "Glycerol-3-phosphate is the backbone of triglycerides (the storage unit of fatty acids in the cell). Glycerol-3-phosphate can form acyl bonds with fatty acid carboxyl groups to attach the fatty acids to the glycerol backbone."),
        37 : (title: "GAPDH",
              description: "Glyceraldehyde-3-phosphate dehydrogenase is an enzyme that catalyzes the redox substrate-level phosphorylation of glyceraldehyde-3-phosphate and NAD+ to 1-3-bisphosphoglycerate and NADH. The NADH generated in this step is not directly used in glycolysis but can be transported to the mitochondria via either the glyerol-3-phosphate shuttle or the malate-aspartate shuttle for energy extraction in the electron transport chain. However, if oxygen is not present, the electron transport chain will not run and NADH will accumulate. Thus, the cell will run out of the NAD+ necessary for this step of glycolysis. Thus, NAD+ can be regenerated in anaerobic conditions. This NAD+ regeneration forms lactic acid from pyruvate (the final glycolysis product) in humans and ethanol from pyruvate in bacteria and yeast. Note that although this step includes a phosphorylation, ATP is not used. Thus, when the phosphate group is removed from 1,3-BPG to form ATP, new energy is being formed (this was not the case with previous phosphorylations as ATP was being used). As a result, 2 ATP and 2 NADH will be generated per glucose molecule in glycolysis (1 ATP and 1 NADH per piece following the aldolase split)."),
        38 : (title: "1,3-BPG",
              description: "1,3-bisphosphoglycerate is the product of the substrate-level phosphorylation of glyceradehyde-3-phosphate. Now that the triose is phosphorylated twice it can be dephosphorylated to yield ATP. The 4 ATP generated from these dephosphorylations (2 ATP per piece following the aldolase split) minus the 2 ATP used in the glycolysis prep phase (hexokinase/glucokinase and phosphofructokinase-1) results in a net ATP yield of 2 ATP in glycolysis."),
        39 : (title: "BPG-mut",
              description: "Bisphosphoglycerate mutase converts 1,3-bisphosphoglycerate to 2,3-bisphophoglycerate. This conversion is important because 2,3-bisphosphoglycerate binds to hemoglobin to cause decreased affinity for oxygen. As a result of the decreased affinity, hemoglobin will unload more oxygen in low-oxygen environments like the muscle. Thus during high altitude adjustment or exercise, the body can generate 2,3-bisphosphoglycerate to unload more oxygen in the tissue."),
        40 : (title: "2,3-BPG",
              description: "2,3-bisphosphoglycerate is a product of the bisphoglycerate mutase conversion of 1,3-bisphosphoglycerate. 2,3-bisphosphoglycerate binds to hemoglobin to cause decreased affinity for oxygen. As a result of the decreased affinity, hemoglobin will unload more oxygen in low-oxygen environments like the muscle. Thus during high altitude adjustment or exercise, the body can generate 2,3-bisphosphoglycerate to unload more oxygen in the tissue."),
        41 : (title: "PGK",
              description: "Phosphoglycerate kinase performs substrate-level phosphorylation on an ADP equivalent using 1,3-bisphosphoglycerate to form 3-phosphoglycerate and ATP. Phosphoglycerate is the first step in glycolysis that generates ATP."),
        42 : (title: "3-PG",
              description: "3-phosphoglycerate is the product of the dephosphorylation of 1,3-bisphosphoglycerate by phosphoglycerate kinase."),
        43 : (title: "PGM",
              description: "Phosphoglycerate-mutase converts 3-phosphoglycerate to 2-phosphoglycerate. This places an alcohol leaving group ready for E1CB elimination in the next step."),
        44 : (title: "2-PG",
              description: "2-phosphoglycerate is the product of the transfer of a phosphate group on 3-phosphoglycerate by phosphoglycerate-mutase."),
        45 : (title: "Eno",
              description: "The enolase enzyme catalyzes the E1CB elimination of the terminal alcohol on 2-phosphoglycerate to form phosphoenolpyruvic acid."),
        46 : (title: "PEP",
              description: "Phosphoenolpyruvate is the product of the alcohol group E1CB elimination of 2-phosphoglycerate by the enolase enzyme."),
        47 : (title: "PK",
              description: "Pyruvate kinase irreversibly dephosphorylates phosphoenolpyruvic acid to form pyruvate and ATP. This is the second ATP-generating step in glycolysis.\n\nControl: Pyruvate kinase is activated via feed-forward activation from fructose-1,6-bisphosphate (an upstream glycolysis intermediate). This feed-forward activation preps pyruvate kinase because any sugar that passes phosphofructokinase-1 to form fructose-1,6-bisphosphate (the main control step of glycolysis) will need to be dephosphorylated by pyruvate kinase."),
        48 : (title: "Pyruvate",
              description: "Pyruvate is the final product of glycolysis following energy extraction. There are now three fates for the pyruvate molecule:\n(1) If oxygen is present, pyruvate will be transferred to the mitochondrial matrix and then converted to acetyl-CoA to enter the TCA cycle for more energy extraction. Oxygen is required because the energy produced will be in the form of reducing equivalents which require the oxygen-dependent electron transport chain to convert to ATP.\n(2) In the absence of oxygen, NAD+ will need to be regenerated to keep running glycolysis (NAD+ is used in the GAPDH step of glycolysis). To regenerate the NAD+ oxidizing equivalent, fermentation will take place. In fermentation in humans, pyruvate is oxidized to lactic acid, and NAD+ is reduced back to NADH in a redox reaction. In bacteria and yeast, a similar redox reaction occurs but ethanol is formed instead of lactic acid.\n(3)During energy deprivation, gluconeogenesis in the liver and renal cortex stabilize blood glucose levels. Because the brain uses glucose as it’s main source of energy, retaining stable glucose in the blood is critical, so we spend energy to regenerate the glucose we used and circulate it in the blood."),
        49 : (title: "PC",
              description: "Pyruvate carboxylase irreversibly uses a CO2 equivalent to form oxaloacetate from pyruvate in the mitochondrial matrix.\n\nControl: Pyruvate carboxylase is activated by acetyl-CoA. Thus, when acetyl-CoA and the TCA cycle is energetically satisfied, the cell will start shunting the extra acetyl-CoA to gluconeogenesis."),
        50 : (title: "OAA (mito)",
              description: "Oxaloacetate in gluconeogenesis is the product of pyruvate carboxylase adding a carboxyl to pyruvate. Because gluconeogenesis occurs in the cytoplasm, oxaloacetate is transported from the mitochondrial matrix to the cytosol via the malate-aspartate shuttle."),
        51 : (title: "MA-s",
              description: "The malate-aspartate shuttle is a method of transporting oxaloacetate from the mitochondrial matrix but also a method of transferring NADH reducing equivalents to the mitochondrial (i.e. those generated in the cytosol from glycolysis).\n\nMechanism: In the cytosol, oxaloacetate and NADH can be converted to malate and NAD+ via malate dehydrogenase. Malate can then enter the mitochondrial matrix. Once inside, malate dehydrogenase can catalyze the reverse reaction to convert malate and NAD+ to oxaloacetate and NADH. Subsequently, oxaloacetate and glutamate are converted to alpha-ketoglutarate and aspartate in the mitochondrial matrix by aspartate transaminase. The resulting aspartate can then exit the mitochondrial matrix and return to the cytoplasm. Once back in the cytoplasm, aspartate transaminase catalyzes the reverse reaction to convert alpha-ketoglutarate and aspartate to glutamate and oxaloacetate. This thus reforms the oxaloacetate so that the shuttle can proceed to transfer more NADH equivalents to the mitochondrial matrix."),
        52 : (title: "OAA (cyto)",
              description: "Oxaloacetate resides in the cytoplasm where further gluconeogenesis steps can occur following transfer from the mitochondrial matrix by the malate-aspartate shuttle."),
        53 : (title: "PEP-CK",
              description: "Phosphoenolpyruvate-carboxokinase uses a GTP to convert cytoplasmic oxaloacetate to phosphoenolypyruvate and CO2. After this conversion, gluconeogenesis can proceed upstream via the reversible steps in glycolysis until reaching the irreversible phosphofructokinase-1.\n\nControl: Phosphoenolpyruvate-carboxokinase is under hormonal control. Glucagon and cortisol activate the enzyme."),
        54 : (title: "Muscle",
              description: "Skeletal muscle can be used as a source of energy during the extended postabsorptive state (starvation). Muscle is built and regenerated with high insulin levels."),
        55 : (title: "Protease",
              description: "Proteases in the skeletal muscle hydrolyze skeletal muscle to form amino acids. Alanine is the main energy contributor from the amino acids. Yet the rest of the amino acids can still be glucogenic (capable of forming glucose via gluconeogenesis) or ketogenic (capable of being converted to ketone bodies):\n- glucogenic: all amino acids except leucine and lysine are glucogenic\n- leucine, lysine, isoleucine, phenylalanine, threonine, tryptophan, and tyrosine can be converted to acetyl-CoA and subsequently ketone bodies\n\nControl: epinephrine, cortisol, and dropping levels of insulin all activate proteases to degrade skeletal muscle."),
        56 : (title: "Ala",
              description: "Alanine is the main energetic contributor from the amino acids. Alanine is released following the protease-induced hydrolysis of skeletal muscle in the hormonal presence of glucagon, epinephrine, or dropping levels of insulin."),
        57 : (title: "ALT",
              description: "Alanine transaminase converts alanine and alpha-ketoglutarate to glutamate and pyruvate. Thus pyruvate is formed from alanine, and in low-energy states in the liver, gluconeogenesis can generate glucose to be released to the blood from this pyruvate."),
        58 : (title: "LDH",
              description: "Lactate dehydrogenase converts pyruvate and NADH to lactate and NAD+. This regenerates the NAD+ oxidative agent necessary to continue glycolysis in the absence of oxygen (used in the GAPDH step of glycolysis)."),
        59 : (title: "Lactate",
              description: "Lactate is a product of the anaerobic burning of glycolysis and regeneration of the NAD+ reagent necessary to continue glycolysis. Lactate will build up in highly anaerobic tissue such as highly active skeletal muscle."),
        60 : (title: "PDH",
              description: "Pyruvate dehydrogenase catalyzes the conversion of pyruvate to acetyl-CoA where it can enter the TCA cycle or ketogenesis. The enzyme additionally reduces an NAD+ equivalent to NADH.\n\nControl: Because pyruvate dehydrogenase is the gatekeeper of the TCA cycle, it is under heavy regulatory control. Negative feedback from acetyl-CoA shuts off pyruvate dehydrogenase. ATP, a signal of energetic satisfaction, activates an enzyme pyruvate dehydrogenase kinase, which in turn phosphorylates and inhibits pyruvate dehydrogenase. ADP, on the other hand, activates a different enzyme pyruvate dehydrogenase phosphatase, which dephosphorylates and activates pyruvate dehydrogenase. Thus, acetyl-CoA is formed when the cell is not energetically satisfied because a substantial amount of additional energy will be generated by passing a pyruvate into the TCA cycle. However, the liver may require the TCA cycle intermediates for metabolic synthesis precursors even if the hepatocytes are energetically satisfied. As a result, insulin in hepatocytes overrides the ATP inhibition and activates pyruvate dehydrogenase to push the TCA cycle even during energetic satiety."),
        61 : (title: "AcCoA (m)",
              description: "Acetyl-CoA is the precursor to the TCA cycle. However, during energetic starvation, hepatocytes can perform ketogenesis to generate ketone bodies that the brain will use for energy in the lack of circulating glucose."),
        62 : (title: "CS",
              description: "Citrate synthase fuses an acetyl-CoA equivalent with an oxaloacetate equivalent to form citrate.\n\nControl: Citrate synthase experiences negative feedback, where it is inhibited by its citrate product. Furthermore, ATP, NADH, and succinyl-CoA, signs of high energy and high throughput through the TCA cycle, all inhibit citrate synthase."),
        63 : (title: "Citrate",
              description: "Citrate is a 6-carbon intermediate in the TCA cycle. It can react to proceed further down the TCA cycle to form isocitrate, but it also can react via the citrate lyase shuttle to form cytoplasmic acetyl-CoA."),
        64 : (title: "CA",
              description: "Cis-aconitase catalyzes the conversion of citrate to isocitrate in the TCA cycle, via the transfer of a hydroxyl group from carbon-3 to carbon-2."),
        65 : (title: "Isocitrate",
              description: "Isocitrate is a 6-carbon intermediate in the TCA cycle."),
        66 : (title: "IDH",
              description: "Isocitrate dehydrogenase catalyzes the conversion of isocitrate to alpha-ketoglutarate and CO2. The enzyme additionally reduces one NAD+ equivalent to NADH.\n\nControl: NAD+ and ADP, signs of low energy, activate the enzyme. On the other hand, NADH and ATP activate the enzyme."),
        67 : (title: "aKG",
              description: "Alpha-ketoglutarate is a 5-carbon intermediate in the TCA cycle."),
        68 : (title: "aKG-DH",
              description: "Alpha-ketoglutarate dehydrogenase catalyzes the conversion of alpha-ketoglutarate to succinyl-CoA and CO2. The enzyme additionally reduces one NAD+ equivalent to NADH.\n\nControl: The enzyme is under negative feedback control, where the succinyl-CoA product inhibits the enzyme. Furthermore, ATP and NADH, signs of energetic satisfaction, inhibit the enzyme. ADP and Ca2+ signs of low energy and energetic demand in active muscle activate the enzyme."),
        69 : (title: "SucCoA",
              description: "Succinyl-CoA is a 4-carbon intermediate in the TCA cycle."),
        70 : (title: "SCDH",
              description: "Succinyl-CoA dehydrogenase catalyzes the conversion of succinyl-CoA to succinate. This conversion releases one GTP equivalent."),
        71 : (title: "Succ",
              description: "Succinate is a 4-carbon intermediate in the TCA cycle."),
        72 : (title: "SDH",
              description: "Succinate dehydrogenase catalyzes the conversion of succinate to fumarate. This enzyme additionally reduces one equivalent of FAD to FADH2. This enzyme is actually Complex II of the electron transport chain, such that the generated FADH2 is funneled directly to the downstream electron transport."),
        73 : (title: "Fum",
              description: "Fumarate is a 4-carbon intermediate in the TCA cycle."),
        74 : (title: "Fase",
              description: "Fumarase catalyzes the conversion of fumarate and H2O to L-malate. Fumarase stereospecifically generates the L isomer of malate."),
        75 : (title: "Malate",
              description: "L-malate is a 4-carbon intermediate in the TCA cycle. Malate is also a contributor to the malate-aspartate shuttle used to transfer cytoplasmic NADH equivalents to the mitochondrial matrix."),
        76 : (title: "MDH",
              description: "Malate dehydrogenase oxidizes the L-malate hydroxyl group to a carbonyl (ester), forming oxaloacetate. This oxidation is paired with the reduction of one NAD+ equivalent to NADH."),
        77 : (title: "OAA",
              description: "Oxaloacetate is a 4-carbon intermediate in the TCA cycle. Oxaloacetate is also a contributor to the malate-aspartate shuttle used to transfer cytoplasmic NADH equivalents to the mitochondrial matrix."),
        78 : (title: "Lipid",
              description: "Ingested lipids consumed from diet begin to be digested into fatty acids in the small intestines. The ingested lipids are emulsified by bile and then broken down by pancreatic lipase/colipase/cholesterol esterase into 2-monoacylglycerol/free fatty acids/cholesterol. Subsequently, micelles are formed to separate the hydrophobic tails on the interior from the hydrophilic heads on the exterior."),
        79 : (title: "ApoB48",
              description: "The ApoB-48 receptor mediates chylomicron secretions (chylomicrons are packaged fats from the small intestines)."),
        80 : (title: "Chylo",
              description: "Chylomicrons are packaged fats from the small intestines, which transport dietary triacylglycerols, cholesterol, and cholesteryl esters from the intestines to the tissue. Chylomicrons are absorbed as chyle into small lymphatic vessels called lacteals in the intestines. They then travel through the lymphatic system to the thoracic duct where they drain into the circulatory system."),
        81 : (title: "VLDL",
              description: "Very-low-density lipoprotein is a lipoprotein with very high fat and low protein percentages. VLDL serves to transport triglycerides and fatty acids from the liver to tissues. Triglycerides and cholesterol are packaged to make VLDL in the liver. Whereas chylomicrons carry exogenous lipids, VLDL carries endogenous lipids."),
        82 : (title: "LPL",
              description: "Lipoprotein lipase functions outside of adipose cells to activate the metabolism of VLDL and chylomicrons. Chylomicrons are metabolized to extract fatty acids and the glycerol backbones, leaving behind Chylomicron Remnants (which are chylomicrons with a lower lipid percentage). VLDL is metabolized similarly to extract fatty acids and the glycerol backbones, but leaving behind IDL (which is VLDL with a lower lipid percentage).\n\nControl: ApoC-II activates lipoprotein lipase. In addition, insulin activates lipoprotein lipase. Insulin, a sign of energetic satisfaction, activates the enzyme because the lysing of VLDL and the chylomicrons is really just preparation for the storage of the lipids in adipose tissue."),
        83 : (title: "HDL",
              description: "High-density lipoprotein is synthesized in the liver and intestines. HDL picks up cholesterol accumulating in blood vessels and delivers cholesterol to the liver and steroidogenic tissues. HDL also transfers apolipoproteins to other lipoproteins. Because of these functions, HDL is considered a \"good\" cholesterol."),
        84 : (title: "LCAT",
              description: "Lecithin-cholesterol acyltransferase is a blood enzyme activated by HDL apoproteins that adds a fatty acid to cholesterol to produce more hydrophobic cholesterol esters that can be stored in a lipoprotein hydrophobic center. ApoA-I activates the LCAT enzyme to catalyze this cholesterol esterification."),
        85 : (title: "HDL+CE",
              description: "High-density lipoproteins with cholesterol-esters are formed after LCAT esterification of HDL. The esterified cholesterol esters are now more hydrophobic such that can be stored in a lipoprotein hydrophobic center."),
        86 : (title: "IDL",
              description: "Intermediate-density lipoprotein is the byproduct after lipoprotein lipase releases some of the lipids from VLDL. IDL can also accept cholesterol esters from HDL+CE."),
        87 : (title: "CETP",
              description: "Cholesterol Ester Transfer Protein facilitates the transfer of cholesterol esters from HDL+CE to IDL. This transfer yields low-density lipoprotein (LDL cholesterol)."),
        88 : (title: "LDL",
              description: "LDL lipoproteins deliver cholesterol into cells for steroid synthesis, liver function, and cell membrane function. The majority of cholesterol is associated with LDL. ApoB-100 permits LDL uptake by the liver to remove LDL from circulation."),
        89 : (title: "Chylo-r",
              description: "Chylomicron remnants are the byproduct of the metabolism and release of lipids in chylomicrons. Chylomicron remnants thus have a lower lipid percentage than chylomicrons but are otherwise similar."),
        90 : (title: "ApoE",
              description: "ApoE facilitates the uptake of chylomicron remnants by the liver and the subsequent release of the cholesterol and triglyceride components."),
        91 : (title: "Chol",
              description: "Cholesterol is a steroid lipid. It is essential for cell membrane fluidity and is also a precursor for metabolic syntheses such as steroid hormone syntheses, bile acid, and vitamin D."),
        92 : (title: "Triglyc",
              description: "Triglycerides (also referred to as triacylglycerols) are the storage form of lipids in the cell. Triglycerides are composed of a glycerol backbone with three ester linkages to fatty acid chains. Triglycerides contain more than twice as much energy as carbohydrates because they are more reduced and are hydrophobic so do not need to be packaged with water (decreasing their packing weight)."),
        93 : (title: "Liver",
              description: "Liver hepatocytes package endogenous triglycerides and cholesterol into newly synthesized VLDL."),
        94 : (title: "FA+glyc",
              description: "Fatty acids and glycerol backbones are released following the metabolism of chylomicrons and VLDL to release the stored lipids. The released fatty acids and glycerol backbones can now be used to synthesize adipose triglycerides."),
        95 : (title: "Adipose",
              description: "Adipose tissue repackages the fatty acids and glycerol backbones released by lipoprotein lipase from chylomicrons and VLDL to form and store triglycerides. These triglycerides will remain inside the adipose cell until energetic demands signal for their release.\n\nControl: Adipocytes synthesize triglycerides in the hormonal presence of insulin."),
        96 : (title: "a-Triglyc",
              description: "Adipose triglycerides are the main storage form of lipid energy. Triglycerides contain more than twice as much energy as carbohydrates because they are more reduced and are hydrophobic so do not need to be packaged with water (decreasing their packing weight). Adipose triglycerides will not be mobilized until energetic demands signal for their release."),
        97 : (title: "HSL",
              description: "Hormone-sensitive lipase mobilizes adipose lipids when energetic demands are present. Adipocyte triglycerides are hydrolyzed to form free fatty acids and glycerol-3-phosphate from the backbone.\n\nControl: Epinephrine, cortisol, and dropping levels of insulin, all signs of lacking energy, activate hormone-sensitive lipase."),
        98 : (title: "FA",
              description: "Free fatty acids are released from the mobilization of adipose triglycerides following the action of hormone-sensitive lipase. The free fatty acids can then be catabolized to extract energy."),
        99 : (title: "FACoA-S",
              description: "Fatty-acid-CoA Synthetase attaches a CoA group to the free fatty acids. This CoA group will allow the fatty acids to travel into the mitochondrial matrix via the carnitine acyltransferase shuttle."),
        100 : (title: "FA-CoA (c)",
               description: "Cytoplasmic fatty-acids-CoA can be transported into the mitochondrial matrix via the carnitine acyltransferase shuttle now that they have a CoA group attached."),
        101 : (title: "CA-s",
               description: "The carnitine acyltransferase shuttle transports fatty-acid-CoA’s from the cytoplasm into the mitochondrial matrix for subsequent catabolism. The cartinite acyltransferase shuttle is actually the rate-limiting step in the mobilization of adipose triglycerides. Because of this slow start, carbohydrates are mobilizes as the first source of energy, even though they are lower density than lipids."),
        102 : (title: "FA-CoA (m)",
               description: "Mitochondrial fatty-acids-CoA can be catabolized in the mitochondria to extract energy."),
        103 : (title: "B-Ox",
               description: "The beta-oxidation spiral catabolizes fatty-acid-CoA’s in 2 carbon chunks. Each spiral of the beta-oxidation spiral releases an acetyl-CoA 2-carbon unit, along with one NADH equivalent and one FADH2 equivalent. If an odd-numbered fatty acid was used as the starting material, a 3-carbon fatty acid propionyl-CoA will remain at the end of the beta-oxidation spiral. Otherwise, the fatty acid can be completely broken down into acetyl-CoA units.\n\nControl: Lipolysis occurs in the presence of hormonal signals for energetic demand. Thus, glucagon activates the beta-oxidation spiral, while insulin inhibits it."),
        104 : (title: "Prop-CoA",
               description: "Propionyl-CoA is a 3-carbon fatty acid. Propionyl-CoA will remain at the end of a beta-oxidation lipolysis spiral if the initial fatty acid starting material is odd-numbered."),
        105 : (title: "PCC",
               description: "Propionyl-CoA Carboxylase attaches a CO2 group to propionyl-CoA to form methylmalonyl-CoA. The enzyme uses biotin (vitamin B7)."),
        106 : (title: "MM-CoA",
               description: "Methylmalonyl-CoA is a 4-carbon lipid intermediate that can reenter the TCA cycle via conversion into succinyl-CoA."),
        107 : (title: "MMM",
               description: "The Methylmalonyl-CoA Mutase enzyme catalyzes the conversion of methylmalonyl-CoA into the TCA cycle intermediate of succinyl-CoA. The enzyme uses cobalamin (vitamin B12). The generated succinyl-CoA can enter the TCA cycle or can be converted to malate for gluconeogenesis in the cytosol. Thus, only odd-chained fatty acids can perform gluconeogenesis."),
        108 : (title: "CL-s",
               description: "The Citrate Lyase Shuttle splits hepatocyte mitochondrial TCA cycle citrate into cytosolic acetyl-CoA and cytosolic oxaloacetate. The oxaloacetate can return to the mitochondrial matrix via the malate-aspartate shuttle. However, the cytosolic acetyl-CoA can be used for anabolic reactions. Cholesterol synthesis and fatty acid synthesis both require cytosolic acetyl-CoA."),
        109 : (title: "AcCoA (c)",
               description: "Cytosolic acetyl-CoA can be used for anabolic syntheses. Cholesterol synthesis and fatty acid synthesis both require cytosolic acetyl-CoA."),
        110 : (title: "Liver SER",
               description: "Cytosolic acetyl-CoA is transferred to the smooth endoplasmic reticulum (SER) in hepatocytes in preparation for cholesterol synthesis."),
        111 : (title: "AcCoA (s)",
               description: "Smooth endoplasmic reticulum acetyl-CoA in hepatocytes can be used to synthesize cholesterol."),
        112 : (title: "HMG-R",
               description: "HMG-CoA reductase synthesizes mevalonic acid from acetyl-CoA in the smooth endoplasmic reticulum of liver hepatocytes. The enzymes uses the NADPH reducing agent for the reaction.\n\nControl: As HMG-CoA reductase is the rate-limiting step in cholesterol synthesis it is the control point for cholesterol synthesis (and thus is a great target for pharmaceutical inhibition like with statin drugs). The enzyme shows negative feedback control, where it is inhibited by its mevalonic acid product. Furthermore, the enzyme is under hormonal control, it is activated by insulin such that cholesterol synthesis occurs only during energetic satiety."),
        113 : (title: "Mev",
               description: "Mevalonic acid is the product of HMG-CoA reductase and an intermediate in the cholesterol synthesis pathway."),
        114 : (title: "IPP",
               description: "Mevalonic acid can be converted into isopentenyl pyrophosphate (IPP). IPP is the precursor for terpenoids like farnesyl-PP, which can be modified to create squalene and then cholesterol."),
        115 : (title: "AC",
               description: "Acetyl-CoA carboxylase attaches a CO2 to acetyl-CoA to create malonyl-CoA to prepare for fatty acid chain synthesis.\n\nControl: Because acetyl-CoA carboxylase is the rate-limiting step in fatty acid synthesis, it is under significant regulatory control. Citrate in the liver mitochondria can activate acetyl-CoA carboxylase via feed-forward activation, prepping the enzyme for the fatty acid synthesis that is coming soon. The enzyme is also under hormonal control. Fatty acids should be synthesized when the cell is energetically satisfied, so insulin activates the enzyme while glucagon inhibits it."),
        116 : (title: "Mal-CoA",
               description: "Malonyl-CoA is a precursor to fatty acid chain synthesis and the product of the rate limiting step in the lipogenesis pathway (acetyl-CoA carboxylase is the rate-limiting step)."),
        117 : (title: "FAS",
               description: "Fatty acid synthase uses NADPH units and acetyl-CoA units to extend the malonyl-CoA starting unit. The enzyme uses vitamin B5.\n\nControl: Fatty acid synthase is under hormonal control. Fatty acids should be synthesized when the cell is energetically satisfied, so insulin activates the enzyme while glucagon inhibits it."),
        118 : (title: "Palm",
               description: "Palmitic acid is the only fatty acid that can be directly synthesized. Palmitic acid is a 16-carbon sugar and is completely saturated."),
        119 : (title: "SER",
               description: "Palmitic acid can be transported to the smooth endoplasmic reticulum (SER) of the hepatocyte for modification."),
        120 : (title: "FA",
               description: "Following modification of palmitic acid in the smooth endoplasmic reticulum of the hepatocyte, the fatty acid is finished and ready to be stored on a triglyceride."),
        121 : (title: "Liver",
               description: "The liver packages the newly formed fatty acids by putting them on a glycerol backbone to form a triglyceride. The triglycerides can then be packaged with hepatocyte-synthesized cholesterol into VLDL for exporting to the tissue."),
        122 : (title: "HMG-S",
               description: "HMG-CoA Synthase in the liver converts acetyl-CoA to HMG-CoA. HMG-CoA can then be converted to ketone bodies by HMG-CoA Lyase, which forms the acetoacetate ketone body. Acetoacetate can be interconverted with a different ketone body, 3-hydroxybutyrate. After the ketone bodies leave the liver, they can be catabolized in the muscle, brain, and renal cortex to form acetoacetyl-CoA, which can then be converted to acetyl-CoA for energy use in the TCA cycle."),
        123 : (title: "Ketones",
               description: "In starvation and high energetic demand, acetyl-CoA will accumulate in hepatocytes because the oxaloacetate that is necessary to push acetyl-CoA into the TCA cycle is being used for gluconeogenesis. As a result, the accumulating acetyl-CoA is converted to ketone bodies (essentially a transportable form of acetyl-CoA). The main ketone bodies used are acetoacetate and 3-hydroxybutyrate (generated by HMG-CoA Synthase and HMG-CoA Lyase). After the release of these ketone bodies from hepatocytes, they travel through the circulatory system to reach the brain, the renal cortex, or the muscle. These tissues contain an enzyme that can catabolize the ketone bodies: thiophorase. This catabolism yield acetyl-CoA units that can be pushed through the TCA cycle to yield energy (since these cells do not perform as much gluconeogenesis as hepatocytes so they have the available oxaloacetate to push acetyl-CoA into the TCA cycle).")
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let selectedCompoundInfo = compoundsInfo[compoundSelectedTag]
        if selectedCompoundInfo != nil {
            titleLabel.text = selectedCompoundInfo?.title
            contentLabel.text = selectedCompoundInfo?.description
        }
        else {
            titleLabel.text = "Oops!"
            contentLabel.text = "Something went wrong, please try again. If problems persist, please restart the app/your device."
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}
